require("autocomands.easy_close_buffers")
require("autocomands.notify_formatter")
require("autocomands.remove_trailing_whitespace")
require("autocomands.highlight_yank")
require("autocomands.restore_cursor")
